version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123!
      POSTGRES_DB: banco_projeto_web
    ports:
      - "5433:5432"
    volumes:
      - dados_pg_16:/var/lib/postgresql/data

volumes:
  dados_pg_16: